### ISSUE TITLE
examples fail to link: undefined symbol: itk::simple::Paste ...

### ISSUE THREAD

**Issue by yurivict** [SimpleITK/SimpleITK#1764] opened 2022-11-16 23:30 UTC
```
ld: error: undefined symbol: itk::simple::Paste(itk::simple::Image const&, itk::simple::Image const&, std::__1::vector<unsigned int, std::__1::allocator<unsigned int> >, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<bool, std::__1::allocator<bool> >)
>>> referenced by HelloWorld.cxx
>>>               Examples/HelloWorld/CMakeFiles/HelloWorld.dir/HelloWorld.cxx.o:(main)
```

Version: 2.1.1
InsightToolkit-5.2.1
clang-14
FreeBSD 13.1

**Comment by blowekamp** [comment] 2022-11-17 13:40
This is because the ITK was not compiled with the [SimpleITKFilters ](https://github.com/SimpleITK/SimpleITK/blob/master/SuperBuild/External_ITK.cmake#L23 )module enabled.

**Comment by blowekamp** [comment] 2022-12-15 18:58
Duplicate of #1765

**Closed by blowekamp** 2022-12-15 18:58 UTC
