### ISSUE TITLE
No method MetaDataDictionaryArrayUpdateOn ()

### ISSUE THREAD

**Issue by Pythonsegmenter** [SimpleITK/SimpleITK#331] opened 2017-10-30 04:41 UTC
Hi,

I tried to get the Dicom  tags along with my images that i need to segment. However when using the series image reader the tags don't come along. I found online that i have to call this method: MetaDataDictionaryArrayUpdateOn ()

However, it doesn't exist. I'm using the latest SimpleITK version 1.0.1 and it is mentioned in the documentation. This is the error: <AttributeError: 'ImageSeriesReader' object has no attribute 'MetaDataDictionaryArrayUpdateOn'>

I tried to solve it using the regular ReadImage in combination with JoinSeries, but that doesn't work since JoinSeries doesn't support 16 bit signed ints. Any other workarounds?

**Comment by zivy** [comment] 2017-10-30 14:15
Hello @Pythonsegmenter,

The issue you are having is that the 1.0.1 release indeed does not include this code update. It will be included in the next release (about mid december). At this point you have two options:
1.a [Build](http://simpleitk.readthedocs.io/en/master/Documentation/docs/source/building.html#recipes-formulas-short-cuts) the current master branch of SimpleITK for your system. 
1.b Follow the example code shown in [this example](https://github.com/SimpleITK/SimpleITK/blob/next/Examples/DicomSeriesReadModifyWrite/DicomSeriesReadModifySeriesWrite.py).
2. Follow the [old example code](https://github.com/SimpleITK/SimpleITK/blob/ad257119b9513f9d8605afcedbb8d0c2ea3a5044/Examples/DicomSeriesReadModifyWrite/DicomSeriesReadModifySeriesWrite.py) and modify it in the future. 

Hope this helps.

**Comment by blowekamp** [comment] 2017-10-30 15:06
A detail regarding you issue with the JoinSeries: Most of the time when you try to read a single slice of a DICOM series, the image is loaded as a 3D image with a z-size of 1 i.e. a 3D slice. The JoinSeriesImageFilter can only join 2D slices to form a 3D volume, it can not join 3D volumes ( or slices ). I suspect that the non-specific error message you got was caused by this unexpected dimension. The JoinSeriesImageFilter certainly support int16 2-D images.

The referenced example accommodates this. However, until 1.1 is released it may be easiest to read the slices and just save the metadata, then read the images again with the series reader.

**Comment by Pythonsegmenter** [comment] 2017-10-30 18:18
Thanks for the quick reply guys! I'll try option 1 first but if it's to complicated (not so experienced with this kind of stuff), than I'll go for option 2. I guess that the disadvantage of option 2 is that it's a bit slower and the code is a bit messier?

**Comment by zivy** [comment] 2017-10-30 20:44
I would go the option 1 route as it is compatible with the next release of SimpleITK, also as you noted the code is cleaner and will be faster as the images are read once (in option 2 we read them twice).

Compiling SimpleITK yourself is definitely doable, even if you are new to this kind of stuff. If you encounter problems following our instructions, then please ask questions on the [discourse forum](https://discourse.itk.org/) and we will guide you, and hopefully improve the instructions at the same time.

**Comment by blowekamp** [comment] 2017-11-14 14:23
I am closing this questions. Please feel free to re-open or create a new issue for discussion as needed.

**Closed by blowekamp** 2017-11-14 14:23 UTC
Labels: Question
