### ISSUE TITLE
How to use sitk's Lua bindings from other interpreters?

### ISSUE THREAD

**Issue by preethamsp** [SimpleITK/SimpleITK#50] opened 2016-07-01 12:47 UTC
Hi,
Thanks for the effort put into this library. It's awesome. Sitk having lua bindings is particularly interesting for torch users like me because the native image library in torch is not very powerful and we tend to do most of our preprocessing in python.
Is there a lua module which is part of the build that I can use from trepl or other interpreters?

Regards,
Preetham.

**Comment by blowekamp** [comment] 2016-07-01 13:31
@dave3d 
This is a duplicate of #49.
I'm going to update the status there.

**Closed by blowekamp** 2016-07-01 13:31 UTC
