### ISSUE TITLE
Unable to open file with Chinese path

### ISSUE THREAD

**Issue by Johnfengyaoxue** [SimpleITK/SimpleITK#1268] opened 2020-12-01 03:26 UTC
Hello，I use SimpleITK in Pyhon,in Win10 computer,The code is as follows

`import` SimpleITK as sitk
reader = sitk.ImageSeriesReader()
filename = "G:\Dicom源文件"
series_id = `reader.GetGDCMSeriesIDs(filename)`

Run the code,the result is as follows:
`D:\Program\Python37\python.exe G:/Python_PyQt/Dicom_Parsing/test.py
WARNING: In D:\a\1\sitk-build\ITK\Modules\IO\GDCM\src\itkGDCMSeriesFileNames.cxx, line 102
GDCMSeriesFileNames (00000192648213A0): No Series were found``

The File "G:\Dicom源文件" is existed,but No Series wre found. Does SimpleITK support Chinese path in Python?

**Comment by zivy** [comment] 2020-12-01 14:19
Hello @Johnfengyaoxue,

Yes, this is [a known bug](https://github.com/SimpleITK/SimpleITK/issues/1255). I am closing this issue as it is a duplicate of that one.

**Closed by zivy** 2020-12-01 14:19 UTC
