### ISSUE TITLE
ResampleImageFilter hangs in SimpleITK 2 and multiprocessing within PyTorch

### ISSUE THREAD

**Issue by fepegar** [SimpleITK/SimpleITK#1239] opened 2020-10-20 21:23 UTC
If `sitk.ResampleImageFilter` is executed using PyTorch multiprocessing capabilities, the program hangs. This doesn't happen with SimpleITK 1.

I have created a minimal working example, runnable online on Google Colab, here: https://gist.github.com/fepegar/77a81c967c92a7c7f0a150cf0152940f

If you run the notebook as it is, it should hang in the last cell.
If you add `!pip install "SimpleITK<2"` at the beginning of the notebook and run it, it should work.

Please let me know if you need any further information.

**Comment by fepegar** [comment] 2020-10-20 21:33
I added the code in the gist, in case the notebook is not rendered correctly on GitHub.

**Comment by blowekamp** [comment] 2020-10-21 12:09
Thank you for your bug report.

Are you able to reduce the minimal example to just the Python standard libraries and SimpleITK ( i.e. no torchio  dependency )? That would greatly expidite the ability to isolate the problem.

Possible work arounds include setting the [number of work units](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1ProcessObject.html#ac3a2fc4905baba0a0e89836f9f9d29a5) and [number of threads](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1ProcessObject.html#ab5c7a8075dafe9dbccb16cc6a48b4209) to 1, or to try [setting the global default multi-threader](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1ProcessObject.html#a709f1c6f88d214826f2e864aff85abd4) to "platform". One change which occurred in SimpleITK 2.0 was using ITKv5's new threading models by default. So I am suspicious it may be related.

**Comment by blowekamp** [comment] 2020-10-21 15:56
By either setting the default threader to "platform" or by setting the resampler's number of work unit's to 1 the script completed.

What is they python light weight threading modules you are using? It is important to try to get this down to a more minimal example. Hopefully just default constructed sitk::Images should be able to reproduce the problem.

**Comment by fepegar** [comment] 2020-10-21 16:00
Thanks for your replies, @blowekamp. I don't have a lot of time to study in details on the configurations you suggested in https://github.com/SimpleITK/SimpleITK/issues/1239#issuecomment-713522752, but I'll write a small example without TorchIO to reproduce this. Also, I don't know the details about how the PyTorch data loader works, and I know very little about parallel processing. Here's the code for the data loader: https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py

I'll come back with a new MWE in a minute.

**Comment by fepegar** [comment] 2020-10-21 16:27
Setup:

```bash
$ conda create -n sitk_test python ipython -y
$ conda activate sitk_test
$ pip install SimpleITK torch torchvision
```

I'm trying to run this script to reproduce this error... but now I'm getting a segmentation fault (`[1]    39496 segmentation fault (core dumped)  python sitk_test.py`) when the filter is executed (**SimpleITK-2.0.1**).

Update: I can run the script on **SimpleITK-2.0.0**.

```python
import torch
import numpy as np
import SimpleITK as sitk


num_images = 10


class MyDataset:
    def __init__(self, paths):
        self.paths = paths

    def __len__(self):
        return len(self.paths)

    def __getitem__(self, index):
        image = sitk.ReadImage(self.paths[index])
        resampler = sitk.ResampleImageFilter()
        resampler.SetInterpolator(sitk.sitkNearestNeighbor)
        resampler.SetReferenceImage(image)
        resampler.SetDefaultPixelValue(0.0)
        resampler.SetOutputPixelType(sitk.sitkFloat32)
        print('Resampling...')
        resampled = resampler.Execute(image)
        print('Resampled!')
        array = sitk.GetArrayFromImage(resampled)
        return array


paths = []
for i in range(num_images):
    image = sitk.GetImageFromArray(np.random.rand(10, 20, 30))
    path = f'/tmp/image_{i}.nii'
    sitk.WriteImage(image, path)
    paths.append(path)

my_dataset = MyDataset(paths)

loader_sp = torch.utils.data.DataLoader(my_dataset, batch_size=4, num_workers=0)
loader_mp = torch.utils.data.DataLoader(my_dataset, batch_size=4, num_workers=2)

print('Extracting batch using one worker...')
batch_sp = next(iter(loader_sp))
print(batch_sp.shape)

print('Extracting batch using two workers...')
batch_mp = next(iter(loader_mp))
print(batch_mp.shape)
```

Output:

```
Extracting batch using one worker...
Resampling...
Resampled!
Resampling...
Resampled!
Resampling...
Resampled!
Resampling...
Resampled!
torch.Size([4, 10, 20, 30])
Extracting batch using two workers...
Resampling...
Resampling...
```

**Comment by fepegar** [comment] 2020-10-21 16:29
> By either setting the default threader to "platform" or by setting the resampler's number of work unit's to 1 the script completed.

Which of these is better? Do you recommend resetting these after the filter has been run?

**Comment by zivy** [comment] 2020-10-21 17:22
I'd go with setting the threading model to "platform". The second option essentially means you'll be working single threaded, so slower. With respect to the segfault that is more serious and we'll have to look into that.

p.s. Which OS and Python version are you using?

**Comment by fepegar** [comment] 2020-10-21 18:50
> I'd go with setting the threading model to "platform" (you don't have to undo/unset this). The second option essentially means you'll be working single threaded, so slower.

Thanks!

> With respect to the segfault that is more serious and we'll have to look into that.

Let me know if I can help.

> p.s. Which OS and Python version are you using?

Google Colab is Linux, and I think it's Python 3.7 or 3.6. I've also reproduced this on Python 3.8, macOS and Linux.

**Comment by zivy** [comment] 2020-10-21 19:35
Update:
Script required slight modification to run on OSX, adding `if __name__ == '__main__':` before the actual work, as otherwise it crashes. This is a [known issue with multiprocessing](https://discuss.pytorch.org/t/multiprocessing-not-working-on-pytorch-on-macbook/80663) on OSX. This modification made it work, no hanging and no need to play with threading model or number of workers/threads (python=3.8.5, torch=1.6.0, sitk=2.0.1).

On unix with same settings as OSX, script hangs.

**Comment by fepegar** [comment] 2020-10-21 19:41
Oh, wow. So did that help for the segmentation fault or for the program hanging? Or both?

Is this just not possible on a Jupyter notebook, then?

**Comment by zivy** [comment] 2020-10-21 19:53
On OSX this addition resolved the segfault, and the script runs fine. In the same environment in a notebook it throws an exception. This doesn't seem to be a SimpleITK issue as I set:
```
def __getitem__(self, index):
    return np.random.rand(10, 20, 30)
```
Please check if you are able to replicate the exception in your notebook with the non simpleitk `get_item` method.

**Comment by fepegar** [comment] 2020-10-21 20:02
My notebook, which I'm just running on Colab, crashes during the filter execution. It doesn't for the NumPy version.

If I downgrade to SITK 2.0.0, it's as expected: no segmentation fault, but the multiprocessing hangs.

**Comment by zivy** [comment] 2020-10-21 20:45
@fepegar, 
Can you check the notebook behavior run on your local machine. I can confirm that the same notebook: (1) on OSX with the above listed package versions and non-simpleitk getitem throws an exception "RuntimeError: DataLoader worker (pid 16566) exited unexpectedly with exit code 1. Details are lost due to multiprocessing." (2) on colab works without a hitch.

@blowekamp Any ideas here, different behaviors in the different environments (command line, notebook, google colab). On google colab it's just impossible to debug because the code either hangs (sitk=2.0.0) or crashes with kernel restart (sitk=2.0.1).

**Comment by fepegar** [comment] 2020-10-21 20:51
I do get that error on macOS:

```
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

I always have issues with multiprocessing and PyTorch when I try things on my macOS. I think that's the error I always get, yes. But I'm not too worried because the `DataLoader` would probably be used only by Linux or Windows users with GPUs that support CUDA.

**Comment by blowekamp** [comment] 2020-10-22 11:33
> > By either setting the default threader to "platform" or by setting the resampler's number of work unit's to 1 the script completed.
> 
> Which of these is better? Do you recommend resetting these after the filter has been run?

IMHO it depends. Does the multi-threading of the resample filter make much of a difference in performance? There is already task level parallelism with the DataLoader, and the images used are relatively small and likely just 2d. So there might not be much performance gain by having two levels of parallelism.

The DefaultThreader is a global property, so setting will effect the behavior of other filter executions, and if it is set my else where in the code then it will effect this execution. On the other hand, setting:
```
        resampler.SetNumberOfThreads(1)
        resampler.SetNumberOfWorkUnits(1)
```
Is just a local change, so it will not be effected by globals changes and therefore be more robust.

**Comment by blowekamp** [comment] 2020-10-22 11:52
> @blowekamp Any ideas here, different behaviors in the different environments (command line, notebook, google colab). On google colab it's just impossible to debug because the code either hangs (sitk=2.0.0) or crashes with kernel restart (sitk=2.0.1

When I tired the original script with Python 3.8 on OSX, python exceptions and error were thrown similar ( as I recall ) to what you posted. However if I build an env with Python 3.7 on OSX I was able to reproduce the reported issue.

The matrix of option and reported behaviors here is too big.
-  Python version 3.7, 3.6
- SimpleITK 1.2.x, 2.0.1, 2.0.0
- execution env: command line, notebooks, google code
- Operating System: Linux, OS X, (Windows hasn't been tested yet, but I'm sure it has problems too).

Some of the issue are inherent with the multithreaded module. Also the PyTouch layer of code is relatively complicated... We need to see if this can be reproduced with just SimpleITK and multiprocessing module.

This is certainly adifficult one...

**Comment by fepegar** [comment] 2020-10-22 12:02
> Does the multi-threading of the resample filter make much of a difference in performance?

I don't know, but I will investigate this. The [`RandomElasticDeformation`](https://torchio.readthedocs.io/transforms/augmentation.html#randomelasticdeformation) transform is, by far, the slowest in my library, so it'd be great to be able to speed it up somehow.

> and the images used are relatively small and likely just 2d

Most TorchIO users apply this to (potentially large) 3D images, sometimes with multiple components (I apply the transform to each component individually, as it seems faster). 

> The matrix of option and reported behaviors here is too big.

Let me know if I can help!

**Comment by blowekamp** [comment] 2020-10-22 12:42
On OS X with Python 3.7, and SimpleITK 2.0.1, I have produces a simplified failing test without `torch`:

```

import multiprocessing as mp
import SimpleITK as sitk
import numpy as np
import os
import threading

num_images = 2


def f( fname ):
    image = sitk.Image(10,12, 14, sitk.sitkUInt8)

    resampler = sitk.ResampleImageFilter()
    resampler.SetInterpolator(sitk.sitkNearestNeighbor)
    resampler.SetReferenceImage(image)
    resampler.SetDefaultPixelValue(0.0)
    resampler.SetOutputPixelType(sitk.sitkFloat32)
    print("Resampling {} pid: {} {}...".format(sitk.ProcessObject_GetGlobalDefaultThreader(), os.getpid(), threading.get_ident(),fname))
    resampled = resampler.Execute(image)

    return resampled


paths = []
for i in range(num_images):
    image = sitk.Image(10,11,12, sitk.sitkUInt8)
    path = f'/tmp/image_{i}.nii'
    sitk.WriteImage(image, path)
    paths.append(path)

print("GlobalDefaultThreader: {}".format(sitk.ProcessObject_GetGlobalDefaultThreader()))
print("GlobalNumberOfThreads: {}".format(sitk.ProcessObject_GetGlobalDefaultNumberOfThreads()))

print("main pid: {} {}".format(os.getpid(), threading.get_ident()))

with mp.Pool(1) as p:
    p.map(f, paths)

```

@fepegar @zivy Please test in your environments and report your configuration and results to confirm consisting "hanging" failing behavior. ( It sounds like the __main__ thing may need to be added with Python 3.8 ).

**Comment by fepegar** [comment] 2020-10-22 14:14
## macOS

**Comment by zivy** [comment] 2020-10-22 14:18
OK, so what I get on OSX, all with sitk=2.0.1:

**python 3.8** 
command-line: frozen with the RuntimeError described above both with the default threading model and when I set it to PLATFORM
notebook: frozen with error message "AttributeError: Can't get attribute 'f' on <module '__main__' (built-in)>" for both threading models.

**python 3.7**
command-line: frozen no error reported with default threading model, but works when set to PLATFORM. 
notebook: frozen no error reported with default threading model, but works when set to PLATFORM.

**Comment by blowekamp** [comment] 2020-10-23 15:07
@dzenanz We are encountering issues with the new ITK Pool threader, and the python multiprocessing module using heavy weight processes. When a spawn processes via multiprocessing use the ITK pool multithread, it does not complete/return. Setting ITK to use only 1 work unit, or the "platform" threader, the process returns. I was able to reproduce this with ITK python too. I am suspicious of ITK's idle threads not terminating as a possible cause, or something related to the conditional variable.

**Comment by gdevenyi** [comment] 2020-10-23 15:10
Does this happen on TBB?

**Comment by blowekamp** [comment] 2020-10-23 15:11
I haven't tested it with that. Do you TBB enable for SimpleITK/ITK python?

**Comment by dzenanz** [comment] 2020-10-23 15:20
The thread pool can deadlock.

Example: assume maxThreads=128. Start a filter which spawns 40 work units (1st generation), they get assigned to 40 threads. Now if each of those work units spawns 4 work units (2nd generation) each, some will get assigned to threads, others will be queued. If the second generation of work units spawns more work units (3rd generation), all the 3rd generation work units will be immediately queued. If 2nd generation work units requires 3rd generation to complete we have a deadlock.

TBB is smarter and avoids deadlocks.

**Comment by blowekamp** [comment] 2020-10-23 15:25
> Example: assume maxThreads=128. Start a filter which spawns 40 work units (1st generation), they get assigned to 40 threads. Now if each of those work units spawns 4 work units (2nd generation) each, some will get assigned to threads, others will be queued. If the second generation of work units spawns more work units (3rd generation), all the 3rd generation work units will be immediately queued. If 2nd generation work units requires 3rd generation to complete we have a deadlock.

I do not believe this is applicable here. The assume that threads are spawning threads. The Python `multiprocessing` module is using *processes*, this is verified in the above code by printing the pid. This is different, more likely related to termination and responding to signal to stop the process or something.

Regardless, this is a very interesting issue/example! Essentially, if the number of Jobs exceeds the number of threads, deadlock will occur since the main/calling/invoking thread is waiting for workers to do the remaining work and there are no workers.

**Comment by dzenanz** [comment] 2020-10-23 15:26
> deadlock will occur since the main/calling/invoking thread is waiting for workers to do the remaining work and there are no workers

Correct!

**Comment by dzenanz** [comment] 2020-10-23 15:28
I suspect I will need https://github.com/InsightSoftwareConsortium/ITK/issues/2050 in order to debug your [MWE](https://github.com/SimpleITK/SimpleITK/issues/1239#issuecomment-714467271).

**Comment by blowekamp** [comment] 2020-10-23 19:51
I tested with the TBB multi-threader and it seems to work OK.

However, forking a multi-threaded process has a very limited guaranteed to work in a POSIX environment. This is because the worker threads could be in a call to a critical section, when the fork occurs, making the state invalid in the child process.

So given this insight, we could set the number of threads in the main calling threads to be 1, but set it in the working threads to be a higher number. Like so:

```
default_number_of_threads = sitk.ProcessObject_GetGlobalDefaultNumberOfThreads()
sitk.ProcessObject_SetGlobalDefaultNumberOfThreads(1)
main_pid = os.getpid()

def f( fname ):

    if (main_pid != os.getpid()):
        sitk.ProcessObject_SetGlobalDefaultNumberOfThreads(default_number_of_threads)

    image = sitk.ReadImage(fname)

    resampler = sitk.ResampleImageFilter()
    resampler.SetInterpolator(sitk.sitkNearestNeighbor)
    resampler.SetReferenceImage(image)
    resampler.SetDefaultPixelValue(0.0)
    resampler.SetOutputPixelType(sitk.sitkFloat32)
    print("Resampling {} pid: {} {}...".format(fname, os.getpid(), threading.get_ident(),fname))
    resampled = resampler.Execute(image)

    return resampled
```

But running both task and job level parallelism may not be benifitial.

[1] https://stackoverflow.com/questions/1073954/fork-and-existing-threads/1074663#1074663
[2] https://www.linuxprogrammingblog.com/threads-and-fork-think-twice-before-using-them

**Comment by Czaki** [comment] 2020-12-02 14:29
I also got hang when using multiprocessing for spawn processes. (Discrete gaussian, Connected components etc). 

using `SimpleITK.ProcessObject_SetGlobalDefaultNumberOfThreads(1)` works for me. 
If I call this function inside process different than main it will not affect the main process? There is no synchronization? or it is separated?

**Comment by blowekamp** [comment] 2020-12-02 15:10
The configuration of the ITK threading must occur before any sub-processes are spawned.

The way processes are [created with fork](https://en.wikipedia.org/wiki/Fork_(system_call)), a copy of everything is created for the new process. So setting calling `SimpleITK.ProcessObject_SetGlobalDefaultNumberOfThreads(1)` will only effect the current process and not all processes. In this context "Global" only reference to the extent of the current process and not all processes.

This is different than if light weight threads were used. With threads "Global" would effect all threads. This is the traditional multi-threading execution environment that ITK(SimpleITK) was initially designed for.

**Comment by fepegar** [comment] 2021-01-27 18:03
Do we have any guidelines/conclusions/recommendations on how to handle this problem?

**Comment by blowekamp** [comment] 2021-01-27 20:34
I believe setting the threader to the "Platform" should restore the behavior. Either by Setting the environment variable "ITK_GLOBAL_DEFAULT_THREADER='Platform'" or by calling `sitk::ProcessObject_SetGlobalDefaultThreader("Platform")`.

Just not I am working on a patch so that the default threader for SimpleITK Superbuilds could be the "Platform".

**Comment by fepegar** [comment] 2021-01-28 22:57
That seems to help on Linux but not macOS. Is that expected?

**Comment by blowekamp** [comment] 2021-01-29 14:39
I recall there being specific OS X with Python 3.8 issue that was traced down to an on Python change in behavior ( not a SimpleITK issue ). I'll have to see if I can find a reference. If I recall correctly a some extra initialization call needed to be done...

**Comment by fepegar** [comment] 2021-01-29 14:40
Let me know if you'd like me to test anything on my macOS.

**Comment by blowekamp** [comment] 2021-02-01 13:47
I believe this may be related to a `multiprocessing` change in Python 3.8 on OS X from using the "fork" to the "spawn" process model. Here is the link to the issue is that was "fixed" by this change:

https://bugs.python.org/issue33725

I am still investigating...

**Comment by blowekamp** [comment] 2021-04-12 17:13
With the merge of PR #1318 the default multithread should be the PlatformMultiThreader. If the problem persists please reopen.

**Closed by blowekamp** 2021-04-12 17:13 UTC
Labels: Bug Report

**Comment by fepegar** [comment] 2021-05-27 17:35
I just tried this with [SimpleITK 2.1 Release Candidate 1](https://discourse.itk.org/t/simpleitk-2-1-release-candidate-1/4153) and it worked fine. Thanks, @blowekamp!

**Comment by blowekamp** [comment] 2021-05-27 18:02
You can find here: https://github.com/InsightSoftwareConsortium/ITK/issues/2069#issuecomment-847478230

a comment about changing the `multiprocess` start method with may also help some situation.
