### ISSUE TITLE
Reading Legacy Converted Enhanced Images

### ISSUE THREAD

**Issue by hackermd** [SimpleITK/SimpleITK#440] opened 2018-04-17 20:59 UTC
I've converted a DICOM Series of Single-Frame MR Images to a Legacy Converted Enhanced MR Image using [MultiFrameImageFactory](http://www.dclunie.com/pixelmed/software/javadoc/com/pixelmed/dicom/MultiFrameImageFactory.html). When I try to load the generated multi-frame image using SimpleITK's `ImageFileReader` class, I get the following error:

```None
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /scratch/dashboard/SimpleITK-OSX10.6-x86_64-pkg/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:97:
sitk::ERROR: Unable to determine ImageIO reader for "<path-to-filename>"
```

Support for Legacy Converted Enhanced Image Storage classes has recently been added to GDCM:
https://github.com/malaterre/GDCM/blob/513a75c2f4dc704549223b831879c4a5fab00076/Source/DataStructureAndEncodingDefinition/gdcmMediaStorage.cxx#L144

Will this functionality be exposed in SimpleITK anytime soon?

**Comment by blowekamp** [comment] 2018-04-18 11:25
Do you have a sample file we could test with?

**Comment by hackermd** [comment] 2018-04-20 18:11
I've used using `MultiFrameImageFactory` to convert a publicly available DICOM series of legacy MR images from the [TCIA Rembrandt collection](https://wiki.cancerimagingarchive.net/display/Public/REMBRANDT):

```None
java -cp "/usr/local/share/pixelmed/pixelmed.jar:/usr/local/share/pixelmed/lib/additional/vecmath1.2-1.14.jar" -Xms512m -Xmx512m -Djava.awt.headless=true com.pixelmed.dicom.MultiFrameImageFactory ~/Desktop/REMBRANDT/900-00-5379/07-08-2005-71974/601-21653 /tmp
```


The thereby generated *LegacyConvertedEnhancedMRImageStorage* SOP Instance `1.3.6.1.4.1.5962.99.1.3827.1771.1524245580372.1.1.0.601.1` can be used to reproduce the error:

```python
import SimpleITK as sitk

reader = sitk.ImageFileReader()
reader.SetFileName('/tmp/1.3.6.1.4.1.5962.99.1.3827.1771.1524245580372.1.1.0.601.1')
reader.Execute()
```

Unfortunately, I can't attach the generated file here.

**Comment by hackermd** [comment] 2018-06-01 16:40
Updating the GDCM code base in ITK solves the problem (see InsightSoftwareConsortium/ITKPythonPackage#105)

It would be great if SimpleITK could be updated once this functionality will become available in ITK.

**Comment by blowekamp** [comment] 2019-06-03 18:33
SimpleITK 1.2.0 contained the patched version of ITK with the GDCM update.

**Comment by hackermd** [comment] 2019-06-04 21:25
@blowekamp thanks for your feedback. Unfortunately, it still doesn't work with version `1.2.0`:

```python
import SimpleITK as sitk

reader = sitk.ImageFileReader()
reader.SetFileName(enhanced_filename)
reader.Execute()
```

```
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /scratch/dashboard/SimpleITK-OSX10.6-x86_64-pkg/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:107:
sitk::ERROR: Unable to determine ImageIO reader for "1.3.6.1.4.1.5962.99.1.3827.1771.1524245580372.1.1.0.601.1"
```

However, it works with ITK version `5.0.0`:

```python
import itk
import numpy as np

ImageType = itk.Image[itk.ctype('signed short'), 3]

series_reader = itk.ImageSeriesReader[ImageType].New(FileNames=legacy_filenames)
legacy_image = series_reader.GetOutput()
legacy_array = itk.GetArrayFromImage(legacy_image)

file_reader = itk.ImageFileReader[ImageType].New(FileName=enhanced_filename)
enhanced_image = file_reader.GetOutput()
enhanced_array = itk.GetArrayFromImage(enhanced_image)
```

**Comment by blowekamp** [comment] 2019-06-04 22:09
What happens if you also call:
```
reader.SetImageIO("GDCMImageIO")
```

Before the execute method.

**Comment by hackermd** [comment] 2019-06-05 12:29
```python
import SimpleITK as sitk

reader = sitk.ImageFileReader()
reader.SetFileName(enhanced_filename)
reader.SetImageIO("GDCMImageIO")
reader.Execute()
```

Doesn't work either.

```
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /scratch/dashboard/SimpleITK-OSX10.6-x86_64-pkg/SimpleITK-build/ITK/Modules/IO/GDCM/src/itkGDCMImageIO.cxx:287:
itk::ERROR: GDCMImageIO(0x7f8b9544bb00): Cannot read requested file
```

**Comment by blowekamp** [comment] 2020-01-08 15:43
This has been fixed in SimpleITK by updated to ITKv5.

**Closed by blowekamp** 2020-01-08 15:43 UTC
Labels: Feedback, Help Wanted

**Comment by hackermd** [comment] 2020-01-20 15:18
Thanks @blowekamp! I hereby confirm that this works now with version ``1.2.4``

**Comment by aksg87** [comment] 2021-01-28 07:15
> This has been fixed in SimpleITK by updated to ITKv5.

@blowekamp @hackermd 

I installed simpleitk recently (2.0.2). Could you clarify the best way to fix this? My understanding is that SimpleITK is a layer on top of ITK. Thanks for any clarification!

**Comment by aksg87** [comment] 2021-01-28 07:37
Here is an [example of a study](https://www.dropbox.com/s/oez9jljwrkby4bz/Ax%20T2%20PROPELLER.zip?dl=0) from the open source TCGA dataset that cases error: `itk::ERROR: itk::ERROR: GDCMImageIO(0x7f88720ebd60): Cannot read requested file`. I also tried to load this study into ITK-snap and the application crashes, but it does load into Horos. I think the issue is a few images in the folder have incorrect dimensions (128x128) instead of (512 x 512), but I wanted to post this here in case anyone else runs into a similar issue.

```
      reader = sitk.ImageSeriesReader()
      reader.SetFileNames(dcm_paths)
      image_3d = reader.Execute()
```

**Comment by blowekamp** [comment] 2021-01-28 12:03
@aksg87 Please create a new issue as I don't believe your issue is related.

**Comment by zivy** [comment] 2021-01-28 19:40
Hello @aksg87,

Can confirm issue with ITK-SNAP, but works with SimpleITK.

Using SimpleITK 2.0.2 I was able to read the image without a problem, other than an ITK generated warning, which is reporting a valid issue. Please try that version with the following code:
```
import SimpleITK as sitk
image_3d = sitk.ReadImage(sitk.ImageSeriesReader_GetGDCMSeriesFileNames('.'))
```

**Comment by aksg87** [comment] 2021-01-28 21:03
> @aksg87 Please create a new issue as I don't believe your issue is related.

Okay, I will create a new issue for this in a moment if I can't find a fix. It maybe an issue with the data! thanks

**Comment by aksg87** [comment] 2021-01-28 21:08
> Hello @aksg87,
> 
> Can confirm issue with ITK-SNAP, but works with SimpleITK.
> 
> Using SimpleITK 2.0.2 I was able to read the image without a problem, other than an ITK generated warning, which is reporting a valid issue. Please try that version with the following code:
> 
> ```
> import SimpleITK as sitk
> image_3d = sitk.ReadImage(sitk.ImageSeriesReader_GetGDCMSeriesFileNames('.'))
> ```

Hi @zivy, thanks for testing this for me. Is there a recommendation on when to use:

`ImageSeriesReader_GetGDCMSeriesFileNames`
vs       
```
reader = sitk.ImageSeriesReader()
reader.SetFileNames(dcm_paths)
```

My goal is converting dicom datasets to NRRD and NIfTI outputs.

**Comment by zivy** [comment] 2021-01-28 22:10
Hello @aksg87,

Always use `ImageSeriesReader_GetGDCMSeriesFileNames` as it returns the list of files sorted along the z direction so that the series reader can create the volume correctly. The series reader just receives a list of images, looks at the distance between the first two along the z direction and assumes that this is the spacing in z for all images.

In a generic setup reading DICOM isn't trivial  as volume slices can reside in different directories or more commonly you have files from multiple series (volumes and other non volume images) in the same directory. 

To get a good handle on DICOM reading, please skim the following:
1. The [Jupyter notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/03_Image_Details.ipynb) illustrating image reading.
2. DICOM handling examples showing [basic reading-writing](https://simpleitk.readthedocs.io/en/master/link_DicomSeriesReader_docs.html), which is what you want, and more advanced [reading-modifying-writing](https://simpleitk.readthedocs.io/en/master/link_DicomSeriesReadModifyWrite_docs.html).
3. [Script](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/characterize_data.py) that deals with a general directory structure, relevant functions are `inspect_single_series` and `inspect_series`.

For any further questions or to continue the discussion please go to [ITK discourse](https://discourse.itk.org/).

**Comment by aksg87** [comment] 2021-01-29 02:06
> Hello @aksg87,
> 
> Always use `ImageSeriesReader_GetGDCMSeriesFileNames` as it returns the list of files sorted along the z direction so that the series reader can create the volume correctly. The series reader just receives a list of images, looks at the distance between the first two along the z direction and assumes that this is the spacing in z for all images.
> 
> In a generic setup reading DICOM isn't trivial as volume slices can reside in different directories or more commonly you have files from multiple series (volumes and other non volume images) in the same directory.
> 
> To get a good handle on DICOM reading, please skim the following:
> 
> 1. The [Jupyter notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/03_Image_Details.ipynb) illustrating image reading.
> 2. DICOM handling examples showing [basic reading-writing](https://simpleitk.readthedocs.io/en/master/link_DicomSeriesReader_docs.html), which is what you want, and more advanced [reading-modifying-writing](https://simpleitk.readthedocs.io/en/master/link_DicomSeriesReadModifyWrite_docs.html).
> 3. [Script](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/characterize_data.py) that deals with a general directory structure, relevant functions are `inspect_single_series` and `inspect_series`.
> 
> For any further questions or to continue the discussion please go to [ITK discourse](https://discourse.itk.org/).

Thanks @zivy. I'll follow up more on the discourse!

I've worked with dicom a good amount but haven't used these libraries before so just catching up to speed.
