### ISSUE TITLE
Python/3.10/lib/python/site-packages/SimpleITK/_SimpleITK.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64)))

### ISSUE THREAD

**Issue by malenaalvarez** [SimpleITK/SimpleITK#1889] opened 2023-02-16 15:38 UTC
I am trying to use it on Mac M2 but it doesn't work. If anyone solved this would be very helpful.

**Comment by blowekamp** [comment] 2023-02-16 15:48
Can you please provide some information about your setup? What python are you running (python.org? anaconda?)? Also the output of the following command would be useful:
`python -c "import platform; print(platform.platform())"`

Additionally, what SimpleITK binary did you install? file name and where did you get it from? command line used and output?

Thanks for the additional information.

**Comment by malenaalvarez** [comment] 2023-02-19 15:41
I am using Visual Studio tu run python 3.10.9, and I installed SimpleITK by using command pip on the terminal. 
The output of the command is: macOS-12.6.2-arm64-arm-64bit
The problem is that SimpleITK it is no compatible with the architecture of M2 chip, but i dont know how to solve it. 
Thanks for the response!

**Comment by dave3d** [comment] 2023-02-20 06:06
How can SimpleITK ARM64 not be compatible with the M2 architecture?  I'm using it on my M1 MacBook Pro.

**Comment by malenaalvarez** [comment] 2023-02-20 14:26
How did you install it? When i run my python code it always comes with the
same error message (the title of the issue).

Thanks!

**Comment by dave3d** [comment] 2023-02-20 14:43
I just did a 'pip install simpleitk'.

Here's SimpleITK working on my M1 MacBook Pro:

```
dchen@L02271105 ITK % python
Python 3.10.9 (main, Jan 11 2023, 09:18:18) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> print(platform.platform())
macOS-12.6.2-arm64-arm-64bit
>>> import SimpleITK as sitk
>>> img = sitk.Image(100,100,sitk.sitkUInt8)
>>> print(img.GetSize())
(100, 100)
>>> 
```

**Comment by malenaalvarez** [comment] 2023-02-20 17:14
I did the same thing and it doesn't work. But i will keep trying by using
your code.

Thanks!

**Comment by malenaalvarez** [comment] 2023-02-22 05:21
Hi,
I was wondering if you are using Visual Studio Code to run
python, because I tried your simple code and still got an error message.
Thanks!

**Comment by dave3d** [comment] 2023-02-24 02:07
I have not used Visual Studio Code on a Mac.  I will give it a try and see what happens.

**Comment by dave3d** [comment] 2023-02-27 21:04
I tried out VS Code on my M1 MacBook Pro.  It uses the python that is installed underneath it.  In my case it was using the python I had installed in homebrew.  And SimpleITK worked find for me.

How did you install python?  What python is VS Code using?

**Comment by malenaalvarez** [comment] 2023-02-28 00:01
I have a M2 MacBook Pro, and I am using Python 3.10.9 with VSCode 1.75.1. I
installed python by downloading it from the official page and downloaded an
extension from VSCode. Any help would be useful.

Thanks!

**Comment by dave3d** [comment] 2023-02-28 15:15
<img width="1240" alt="Screen Shot 2023-02-28 at 10 06 34 AM" src="https://user-images.githubusercontent.com/611581/221894225-572bf23b-4d37-4804-a410-28cf19ff5768.png">

OK, I was able to get SimpleITK working with Visual Studio Code on my M1 MacBook Pro, as you can see in my screenshot.  For me, it's picking up the python executable that I installed with homebrew.  You can see in the lower section of the picture that it is using ' /Users/dchen/homebrew/bin/python3.11'.

Note that VSC did not actually install python, it's just using one that it found locally.  So in your case, I think the issue is not with VSC but with your installation of python.  It is strange that you have a ARM python executable but somehow have an x86_64 version of SimpleITK installed inside of it.

My suggestion is to remove that SimpleITK package and directly down the exact SimpleITK package that you need.  Here's a link to the version you want I believe.

https://files.pythonhosted.org/packages/2c/e3/a3c7234b40a5a2e4f610b2d699078e540f5b0c8521331eda3c3c7b9294dc/SimpleITK-2.2.1-cp310-cp310-macosx_11_0_arm64.whl

Then do a 'pip install' with that file.

**Comment by zivy** [comment] 2023-04-13 18:08
This issue appears to be resolved, closing.

**Closed by zivy** 2023-04-13 18:08 UTC
Labels: Question
