### ISSUE TITLE
FOV and pixelspacing mismatch issue 

### ISSUE THREAD

**Issue by subhajitchatu** [SimpleITK/SimpleITK#576] opened 2018-09-25 05:02 UTC
Hi,

I am getting a new issue when  I am trying to register two images using simpleITK.
1. Images have different matrix size .
  eg.
    fixed: (512,512,60)   
    moving: (480,480,60)
2. Images have different FOV ( voxel size, resolution, pixel spacing etc. are different)
    fixed: 
  eg.
    fixed: (390mm,390mm,60)
    moving: (340mm,340mm,60)

So, after registering them using sitkAffineTransformation , I resampled the output image according to the fixed image using SetSpacing(), SetOrigin(), SetDirection(). The problem I have found that
1. The output image has same FOV and matrix size as fixed image. But the FOV is shrinking, i.e it is taking very small area and I could not able to match in with the fixed image in my further processing.

2. When I  tried to use other methods like BSpline. The output image was filled with zeros only. It works only with Affine.

3. In case of affine transform , the output image was having a translation also, which was not expected because in the the moving image, there is no translation.

Please let me know if I need to do some other steps in this case of FOV, pixel size mismatch.

Thanks

**Comment by zivy** [comment] 2018-09-25 13:40
Hello @subhajitchatu,

Not sure what you mean by "resampled the output image according to the fixed image using SetSpacing(), SetOrigin(), SetDirection()."

Did you call the procedural resample method? Something like:
```
moving_resampled = sitk.Resample(moving_image, fixed_image, final_transform, sitk.sitkLinear, 0.0, moving_image.GetPixelID())
```
Also, not sure what you mean by FOV is shrinking. The "moving_resampled" image above will have the same spatial extent as the fixed_image. Are you getting mostly pixels with the default pixel value (0.0 in the code  above)? You can set it to some other value to distinguish between points mapped outside the moving image and pixels with a value of 0.0 in the moving image.

You are also concerned that the affine transformation had a translational component. This is a valid result when you use an affine transformation as your transformation model. What is the expected transformation? Is it only rotation or are you dealing with a deformation between the two images?

You may  find the read-the-docs page on [general SimpleITK concepts](https://simpleitk.readthedocs.io/en/master/Documentation/docs/source/fundamentalConcepts.html#) (transformations, resampling etc.) useful and the [registration Jupyter notebooks](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks) that include resampling after registration (they all start with 6*).

**Comment by subhajitchatu** [comment] 2018-09-25 14:12
Hi @zivy ,

I was just trying the below code

`def GlobalAffineRegistration(fixed,moving):

       moving = sitk.Cast(moving, fixed.GetPixelID())
       ConstPixelSpacing = list(fixed.GetSpacing())
       Origin = list(fixed.GetOrigin())
       Direction = list(fixed.GetDirection())
       moving.SetSpacing(ConstPixelSpacing)
       moving.SetOrigin(Origin)
       moving.SetDirection(Direction)
       initialTx = sitk.CenteredTransformInitializer(fixed, moving, sitk.AffineTransform(fixed.GetDimension()))
       R = sitk.ImageRegistrationMethod()
       R.SetMetricAsJointHistogramMutualInformation(32)

       R.SetOptimizerAsGradientDescent(learningRate=1.0,
                                       numberOfIterations=100,
                                       estimateLearningRate = R.EachIteration)

       R.SetOptimizerScalesFromPhysicalShift()
       R.SetInitialTransform(initialTx,inPlace=False)
       R.SetInterpolator(sitk.sitkLinear)
       outTx = R.Execute(sitk.Cast(fixed,sitk.sitkFloat32), sitk.Cast(moving,sitk.sitkFloat32))

       resampler = sitk.ResampleImageFilter()	
       moving = sitk.Cast(moving, fixed.GetPixelID())
       resampler.SetTransform(outTx)
       resampler.SetReferenceImage(fixed)
       resampler.SetInterpolator(sitk.sitkLinear)
       out = resampler.Execute(moving)
       Origin = list(fixed.GetOrigin())
       Direction = list(fixed.GetDirection())
       out.SetSpacing(ConstPixelSpacing)	
       out.SetOrigin(Origin)
       out.SetDirection(Direction)				
       sitk.WriteImage(out,outFileName)
`

Using this code I find the below output, where I tried to register moving and fixed image with different modality and may have different fov, pixel spacing etc. When I use bspline , whole image is having 0.0.
I could not able to figure out the problem.

![fixed1](https://user-images.githubusercontent.com/4659247/46019612-1ca91480-c0fa-11e8-836d-efc4136195f9.png)
![moving1](https://user-images.githubusercontent.com/4659247/46019616-20d53200-c0fa-11e8-93f9-aa112b34c051.png)
![output1](https://user-images.githubusercontent.com/4659247/46019635-29c60380-c0fa-11e8-8864-94f8bde62ea2.png)

**Comment by zivy** [comment] 2018-09-25 17:03
It is unclear why you are modifying the moving image before registration, this is not a standard thing to do. What I expect the code to look like is:
```
def GlobalAffineRegistration(fixed,moving):

   initialTx = sitk.CenteredTransformInitializer(fixed, moving, sitk.AffineTransform(fixed.GetDimension()))
   R = sitk.ImageRegistrationMethod()
   R.SetMetricAsJointHistogramMutualInformation(32)

   R.SetOptimizerAsGradientDescent(learningRate=1.0,
                                   numberOfIterations=100,
                                   estimateLearningRate = R.EachIteration)

   R.SetOptimizerScalesFromPhysicalShift()
   R.SetInitialTransform(initialTx,inPlace=False)
   R.SetInterpolator(sitk.sitkLinear)
   outTx = R.Execute(sitk.Cast(fixed,sitk.sitkFloat32), sitk.Cast(moving,sitk.sitkFloat32))

   out = sitk.Resample(moving, fixed, outTx, sitk.sitkLinear, 0.0, moving.GetPixelID())

   #outFileName is defined outside the function and not passed as argument, better to pass
   #as argument
   sitk.WriteImage(out,outFileName) 
```

Please take a look at [this related registration example](https://simpleitk.readthedocs.io/en/master/Examples/ImageRegistrationMethod1/Documentation.html) .

**Comment by subhajitchatu** [comment] 2018-09-25 17:51
Hi @zivy ,

Thanks a lot for you comment. 

As I have stated earlier, I have also tried the same thing(without touching moving image). You can see the output of that operation in the last three images. In the last image, which is after registration image, having an unwanted translation along Y direction. 

However, in some cases, the output image's field of view is shrinking(zooming out) with no changes in shape. (Just lookwise smaller). I was surprised and wondered if the .nii file has some wrong header information, GetSpacing() will take that value only?

I am still stuck in this issue. 

Thanks

**Comment by zivy** [comment] 2018-09-25 18:51
OK. So when you ran the code which is similar to what I gave above, you got an output that looked as if you were zoomed out? This can happen with an affine transformation as it admits scale. To see if this is the issue, use a rigid transformation where it is not possible to get scaling.

If you still get scaling then the problem is somewhere else (not the registration). Possibly the combination of file format you save and viewer you are using. The nifti file format supports non-isotropic pixel spacing, but if your viewer doesn't know how to deal with it the image may be squashed. For instance, saving a non-isotropic image into jpg will give you the following result:

![image](https://user-images.githubusercontent.com/338645/46035896-2cacfe00-c0d2-11e8-9dc4-6e1c4fbd0446.png)

Be aware that only on very rare occasions do you need to explicitly change spacing (SetSpacing()). When reading/writing the image it is implicitly taken care of by SimpleITK. You can check via GetSpacing() before/after reading/writing.

Please also try running the code I gave above and post the results if the problem persists.

**Comment by subhajitchatu** [comment] 2018-09-25 19:05
Hi @Zivy

Thanks for this feedback. Actually I have tried Euler3DTransformation , but the results are same. The raw images were in dicom, I have simply read them in nifti , processed and saved in nifti. 

I need to do explicite setspacing function call. Simpleitk Registration didn't take care of different pixel spacing between moving and fixed image. So, if I don't set pixel spacing, the output image in nifti will have FOV size = Matrix size.

For eg:

Fixed image = FOV: (390 mm , 390 mm) ; Matrix size : (512,512)
Moving image = FOV: (340mm , 340 mm); Matrix size : (512,512)

After registration, if I don't set pixel spacing it would be 
FOV: (512,512) and Matrix size : (512,512)

I didn't understand why this is happening? I also agree , there is something in reading and writing the image. What are other way to check if things are correct or not?

Thanks

**Comment by zivy** [comment] 2018-09-25 19:13
What you are describing shouldn't happen, so I am a bit at a loss. The resampled moving image using the transformation should have the same FOV as the fixed image (it may be empty or show bad registration results but the size is definitely that of the fixed image).

Can you share the two 2D images you are trying to register?

**Comment by subhajitchatu** [comment] 2018-09-25 19:18
Hi @Zivy,
I know that shouldn't happen. I am also surprised, that's why I asked the question here. I have used these registeration techniques  in manyges before, suddenly I have come across such issue.
Can you please tell me when it will be empty? Because if I apply random sampling or bspline on these images, output is coming empty. 
I have already attached a slice from both fixed and moving image in my second message in this thread. Did you get it? I will upload 3D stacks as well, so that you can help me in finding the problem. 

Thanks

**Comment by zivy** [comment] 2018-09-25 19:46
The image will be empty when the transformation you got from registration maps all of the region of the fixed image outside of the moving image. Usually happens when the registration completely fails or when the fixed image region isn't defined correctly (e.g. you called the resample filter's SetOutputSpacing with an incorrect value).

The slice images you attached in the message are in png format which assumes isotropic pixels which is fine given that it is a single slice (usually in MR/CT they will be isotropic in the slice plane). 

As you are working with a 3D volume then likely the spacing in Z direction is larger than x-y.  Please provide a link from which we can download the 3D stacks, possibly as two files in nifti or mha format (fixed.nii, moving.nii)?

**Comment by subhajitchatu** [comment] 2018-09-25 20:19
Hi @zivy ,


Thanks for your kind reply. Please check the below link to download fixed, moving images. I have also included output image using the affine transformation. If possible please let me know what you are getting using Bspline on these images. I am getting zeros all over. Only using affine transformation , I have got some output(not satisfactory though).

[https://www.dropbox.com/s/qsxjfu69ihdpkk6/images.zip?dl=0]


Thanks

**Comment by zivy** [comment] 2018-09-25 23:48
Hi @subhajitchatu,

Thanks for posting the volumes. My first observation is that there is a significant scale difference between the two (measured using ITK-SNAP measurement tool). This means an affine transform is likely more appropriate than rigid. So I wrote the simplest version (single scale) which is below. It works and the resulting images are aligned.

```
import SimpleITK as sitk

fixed_image = sitk.ReadImage('fixed.nii', sitk.sitkFloat32)
moving_image = sitk.ReadImage('moving.nii', sitk.sitkFloat32)

# Initialize transformation
initial_transform = sitk.CenteredTransformInitializer(fixed_image, 
                                                      moving_image, 
                                                      sitk.AffineTransform(3),
                                                      sitk.CenteredTransformInitializerFilter.GEOMETRY)

# Sample and save after initialization.
moving_resampled = sitk.Resample(moving_image, fixed_image, initial_transform, sitk.sitkLinear, 0.0, moving_image.GetPixelID())
sitk.WriteImage(moving_resampled, 'initial_moving_resampled.nii')

# Perform simplest (single level) registration
registration_method = sitk.ImageRegistrationMethod()
registration_method.SetMetricAsMattesMutualInformation(numberOfHistogramBins=50)
registration_method.SetMetricSamplingStrategy(registration_method.RANDOM)
registration_method.SetMetricSamplingPercentage(0.05)
registration_method.SetInterpolator(sitk.sitkLinear)
registration_method.SetOptimizerAsGradientDescent(learningRate=1.0, numberOfIterations=300, convergenceMinimumValue=1e-6, convergenceWindowSize=10)
registration_method.SetOptimizerScalesFromPhysicalShift()
registration_method.SetInitialTransform(initial_transform, inPlace=False)
final_transform = registration_method.Execute(fixed_image, moving_image)

print('Optimizer\'s stopping condition, {0}'.format(registration_method.GetOptimizerStopConditionDescription()))

# Sample and save after registration.
moving_resampled = sitk.Resample(moving_image, fixed_image, final_transform, sitk.sitkLinear, 0.0, moving_image.GetPixelID())
sitk.WriteImage(moving_resampled, 'final_moving_resampled.nii')
```
Please close the issue if this resolved your problem.

**Comment by subhajitchatu** [comment] 2018-09-26 03:36
Hi @Zivy

Thanks for your help. I would like to know what do you mean by scale difference? Did u mean intensity scale? It will be different because they are multimodal. I couldn't able to find what was wrong in the first code I posted here(without touching moving image) . Because using that code, it gave me some strange output. So do you think after this alignment, Bspline will also work?
It is not clear what do mean by 'single scale'? Where did u mention that in your code?

 Anyway Let me check and close this issue first.

Thanks

**Comment by subhajitchatu** [comment] 2018-09-26 12:46
Hi @zivy ,

Thanks a lot. It works. I have checked my code,  I missed 'sitk.CenteredTransformInitializerFilter.GEOMETRY' this parameter. Does CenteredTransformInitializer() take MOMENT parameter by default? Because this is the only thing I skipped. I am little confused. Please let me know your view.

Thanks

**Comment by zivy** [comment] 2018-09-26 13:37
Happy to see this resolved your problem.

Yes, the default for CenteredTransformInitializer is MOMENTS ([see documentation](https://itk.org/SimpleITKDoxygen/html/namespaceitk_1_1simple.html#aaf9e4fbf1f3315fc240973a58a9d5cf5)).

I will close this issue now.

**Closed by zivy** 2018-09-26 13:37 UTC

**Comment by subhajitchatu** [comment] 2018-09-26 16:17
Hi @zivy ,

I am really sorry. I need to reopen the same issue for another case similar as before. Here the same code failed. The same code I tried in the below image. Can you please suggest what's going on? This is also a multimodal 3D registration case.

https://www.dropbox.com/s/xjkz3n2lzcw5yr5/images.rar?dl=0

The changes are FOV (voxel size) and Image type are different here. I have used sitk.Cast() and casted both images to unsigned 16 bit integer. If I use sampling 0.05, It gave output with all 0 (moving image has fewer voxels present than fixed image) . However, when I removed the random sampling part and tried again, it gave output as I put here. It's very strange behavior. I couldn't able to find the problem here with basic affine transformation as you suggested.

Thanks

**Comment by subhajitchatu** [comment] 2018-09-26 16:40
Hi @zivy ,

I am really sorry. I need to reopen the same issue for another case similar as before. Here the same code failed. The same code I tried in the below image. Can you please suggest what's going on? This is also a multi-modal 3D registration case.

https://www.dropbox.com/s/1w0my11a2kpprr9/images_new.rar?dl=0

The changes are FOV (voxel size) and Image type are different here. I have used sitk.Cast() and casted both images to unsigned 16 bit integer. If I use sampling 0.05, It gave output with all 0 (moving image has fewer voxels present than fixed image) . However, when I tried with 25% random sampling points , it gave output as I put here in output.nii. It's very strange behavior. I couldn't able to find the problem here with basic affine transformation as you suggested.

Please give me your kind suggestion.

Thanks

**Comment by zivy** [comment] 2018-09-26 17:29
Hi @subhajitchatu ,

I see this is a PET to MR registration this time. Running the registration code as is with the images you gave worked for me, will require FFD registration for good results, but affine gets reasonably close.  I am not sure what you are doing differently (your output was very different from what I got).

Also, there is no need to cast the images to 16 bit integer as later they are cast to 32 or 64 bit float for the registration process. Different FOV and pixel types are implicitly taken care of in the registration framework.

Unfortunately I cannot further assist you with your specific registration task as it is not a problem with the SimpleITK registration framework, rather you need guidance/help with respect to general knowledge about registration algorithms, something we simply don't have resources to support.

**Comment by subhajitchatu** [comment] 2018-09-26 17:32
Thanks a lot @zivy. By the way both the images are MRI images. I am just running the code you suggested above   Anyway I am really grateful for your assistance. Closing this issue.
