### ISSUE TITLE
Unable to display RGB images

### ISSUE THREAD

**Issue by pranitapradhan91** [SimpleITK/SimpleITK#485] opened 2018-06-06 11:35 UTC
I am new to SimpleITK and have done the anaconda based installation. I want to read an RGB image (.png file) and display it. However, I get an error 

> RuntimeError:
 Exception thrown in SimpleITK Show: C:\Users\dashboard\Miniconda3\conda-bld\simpleitk_1521730316398\work\Code\IO\src\sitkShow.cxx:495:
sitk::ERROR: No appropriate executable found.

Here is my code,
`fixed_image = sitk.ReadImage('...../composite.png')
sitk.Show(fixed_image)`

Can someone tell me whats wrong here? Or is it some installation problem?
Thanks

**Comment by zivy** [comment] 2018-06-06 12:38
Hello @pranitapradhan91 

This is as you suspected an installation issue. The problem is with your Fiji installation, which is the viewer SimpleITK uses in the Show command.

If you have not done so:
[Download and install](https://fiji.sc/#download) the Fiji image viewer. 
* On Windows: Install into your user directory (e.g. C:\Users\[your name]\Fiji.app).
* On Linux: Install into ~/bin .
* On Mac: Install into /Applications .

If this resolves your problem please close the issue, otherwise we will need [additional details](https://github.com/SimpleITK/SimpleITK#report-an-issue).

**Comment by pranitapradhan91** [comment] 2018-06-06 14:32
I want to address two more problems in this regard.

1. Fiji is stored in user directory. C:/users/si62qit/Documents/Fiji/Fiji.app
Looks correct to me at least but I am no expert. So please correct me if its wrong.

2. I converted the .png image to .mha using Fiji, read it in python and then displayed it using myshow  given here ([http://simpleitk-prototype.readthedocs.io/en/latest/user_guide/myshow.html]. Something like this,
 `fixed_image = sitk.ReadImage('.../composite.mha')` 
`myshow(fixed_image)`
Now, this worked. I could see the RGB image. However, when I check the depth of this image `print(fixed_image.GetDepth())`, this gives me '0' as output. How it is this possible? Shouldn't it be 3 for RGB images?
Note- I was not able to display .png images using myshow(). That is why I converted them to .mha

I am doing something really wrong here?
Thanks

**Comment by zivy** [comment] 2018-06-06 15:43
Hello @pranitapradhan91,

1. Your Fiji install is under "Documents" which is not the expected location (i.e. C:\users\si62qit\Fiji.app).

2.  Not sure why you could not display the image using myshow, this doesn't have to do with the file format on disc (mha or png), this may have to do with the format of fixed_image in memory, possibly you read them slightly differently. The depth of the image is correct, a 2D RGB image has a depth of zero (it has 3 channels but is 2D).

Please read [this page](https://simpleitk.readthedocs.io/en/master/Documentation/docs/source/fundamentalConcepts.html) for a general introduction to the SimpleITK concepts. You may also want to take a look at the [SimpleITK Jupyter notebooks](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks) to experiment with these concepts.

**Comment by pranitapradhan91** [comment] 2018-06-07 15:52
Thank you.
I am now able to work with Fiji as default viewer after making the suggested changes. I am able to display all types of images using myshow and sitk.Show except one batch of images. I don't know why this happens. I converted this whole batch of images from .png into .jpg to make it work.

**Comment by zivy** [comment] 2018-06-07 16:08
Looks like you resolved the problem, so I am closing the issue. Feel free to reopen if you have further questions on the subject or create a new issue if you encounter new problems.

**Closed by zivy** 2018-06-07 16:08 UTC
