### ISSUE TITLE
Elastix throws LargestPossibleRegion != BufferedRegion on Windows 7

### ISSUE THREAD

**Issue by kaspermarstal** [SimpleITK/SimpleITK#1732] opened 2022-10-14 08:34 UTC
Hi all,

On Windows 7, when running elastix either via SimpleITK.ElastixImageFilter or the standalone executable in Examples/elx.cxx, [this cast to a SimpleITK image](https://github.com/SimpleITK/SimpleITK/blob/f5a03d52ee32a5de4488e7ac01c06eaa9a8cf260/Code/ElastixTransformixWrappers/src/sitkElastixImageFilterImpl.cxx#L251) throws the ["The image has a LargestPossibleRegion of [x, y, z] while the buffered region is [0,0,0]"](https://github.com/SimpleITK/SimpleITK/blob/f5a03d52ee32a5de4488e7ac01c06eaa9a8cf260/Code/Common/src/sitkPimpleImageBase.hxx#L77) error. 

This is fixed by adding the line

    elastixFilter->GraftOutput( Cast( this->GetFixedImage( 0 ), sitkFloat32 ).GetITKBase() );

just prior to [calling Update() on the elastixFilter](https://github.com/SimpleITK/SimpleITK/blob/441fc34e9337433c262dec7b23fc90a557bfac60/Code/ElastixTransformixWrappers/src/sitkElastixImageFilterImpl.cxx#L249) in order to copy output information before running the filter, like we usually do for mini-pipelines e.g. [here](https://github.com/InsightSoftwareConsortium/ITK/blob/05accd95f44914c7a23fd57d78466acae71e5d32/Modules/Filtering/MathematicalMorphology/include/itkGrayscaleMorphologicalClosingImageFilter.hxx#L164).  

Does anyone know why this might be happening?

The weird thing is that the tests run just fine. I only see this on Windows 7, and given how old this platform is, I don't know if it makes sense to fix it. But I am happy to prepare a PR if needed.

**Comment by blowekamp** [comment] 2022-10-14 10:31
Does replacing `elastixFilter->Update();` with elastixFilter->UpdateLargestPossibleRegion();` also work?

**Comment by blowekamp** [comment] 2022-10-14 11:32
Also I don't believe the elx.cxx example is actually run in a test. That would be a good place to start to verify behavior.

ref: #1664

**Comment by kaspermarstal** [comment] 2022-10-15 08:27
> Does replacing `elastixFilter->Update();` with elastixFilter->UpdateLargestPossibleRegion();` also work?

No, `elastixFilter->UpdateLargestPossibleRegion()` does not work.

**Comment by blowekamp** [comment] 2022-10-17 12:36
@kaspermarstal Would you like to tackle issue #1664 to get the examples running as tests? This will help to determine if the error is occurring on another platform.

**Comment by kaspermarstal** [comment] 2022-10-22 16:23
@blowekamp yes I can do that.

**Comment by blowekamp** [comment] 2022-10-26 17:17
The default option for "SimpleITK_EXPLICIT_INSTANTIATION" should be off. Perhaps it should be disabled?

**Comment by blowekamp** [comment] 2022-10-26 20:08
I was unable to reproduce this error message on a linux or Mac system. Perhaps there is some in consistent compilation flags or CMake options between SITK and ELX?

**Comment by kaspermarstal** [comment] 2022-10-28 08:25
Did you test with debug or release? Release works fine on my ubuntu system, only debug does not work.

**Comment by blowekamp** [comment] 2022-10-28 12:06
@kaspermarstal I am able to reproduce the failure of the  `CXX.Example.Elastix` test on all my system. However, the linking issue in Debug related to multiple definitions I am not able to reproduce.

**Comment by blowekamp** [comment] 2023-01-03 18:46
This issue has been addressed in #1735

**Closed by blowekamp** 2023-01-03 18:46 UTC
Labels: Bug Report, SimpleElastix
