### ISSUE TITLE
LabelStatisticsImageFilter

### ISSUE THREAD

**Issue by emiltoft** [SimpleITK/SimpleITK#1141] opened 2020-06-26 09:31 UTC
Using the LabelStatisticsImageFilter with the current latest prerelease: SimpleITK-2.0.0rc1.post295 the label order is not identical to current release version: SimpleITK-1.2.4. Additionally, a warning is thrown in debug-mode

I get the following warning:
WARNING: In /Users/runner/runners/2.170.1/work/1/sitk-build/ITK/Modules/Core/Common/src/itkProcessObject.cxx, line 1184
LabelStatisticsImageFilter (0x7fd1e04f7d40): Output doesn't exist!

**Comment by blowekamp** [comment] 2020-06-29 11:41
Do you have sample code and date to reproduce your issue? Does SimpleITK 2.0rc1 also have the same issue?

**Comment by emiltoft** [comment] 2020-06-29 11:57
Yes, I get the same error and label order using SimpleITK 2.0rc1. 
Sample code are displayed below:

seg = sitk.ReadImage("image_Segmentation.mha")
labels_stats = sitk.LabelStatisticsImageFilter()
labels_stats.Execute(seg, seg)
print(labels_stats.GetLabels()) #(Should print (0,1,2,3))

Output:
WARNING: In /Users/runner/runners/2.165.1/work/1/sitk-build/ITK/Modules/Core/Common/src/itkProcessObject.cxx, line 1167
LabelStatisticsImageFilter (0x7fe57b4cac50): Output doesn't exist!

(1, 3, 2, 0)

**Comment by blowekamp** [comment] 2020-06-29 12:48
I am unable to reproduce the error with the data sets I have. Are you able to synthetically generate a data set to produce the error message.

Also, please review how to report and issue: https://github.com/SimpleITK/SimpleITK#report-an-issue To provide needed information about the operating system, python versions and distribution you are using.

Thanks.

**Comment by emiltoft** [comment] 2020-06-29 14:15
To set the SimpleITK version for 1.0.1 (I get the same using v.1.2.4) and (2.0rc1) I used  1) and 2), respectively.
1) pip install SimpleITK==1.0.1
2) pip install --upgrade --pre SimpleITK --find-links https://github.com/SimpleITK/SimpleITK/releases/tag/v2.0rc1

I managed to generate a synthetic data that could reproduce the error. The error message only appers during debug mode in PyCharm (2019.3.4, Community Edition).

CODE
import os
import sys
import SimpleITK as sitk
import platform

_DIR = os.path.dirname(__file__)

def generating_synthetic_image():
    print("Generating synthetic image...")
    img = sitk.Image(338,341,334,sitk.sitkUInt8)

    voxel = sitk.GetArrayFromImage(img)
    voxel[200:300,80:230,80:230] = 1

    voxel[50:150,90:220,90:220] = 2
    voxel[50:150, 260:300, 80:230] = 3

    img_out = sitk.GetImageFromArray(voxel)
    img_out.SetOrigin((1.33, -52.2, -171))
    img_out.SetSpacing((0.4883, 0.4883, 0.625))

    sitk.WriteImage(img_out, f"{_DIR}/syntetic_image.mha")

    return img_out, "Synthetic image"

def test(img):

    print(f"Testing: {img[1]}")

    labels_stats = sitk.LabelStatisticsImageFilter()
    labels_stats.Execute(img[0], img[0])
    print(labels_stats.GetLabels())     #should print (0,1,2,3)


def reading_true_image():
    print("Reading true image...")
    return sitk.ReadImage(f"{_DIR}/image_Segmentation.mha"), "True image"

def version():
    print(f"Operating system: {platform.platform()}\n")
    print(f"Python version: {sys.version}\n")
    print(f"SimpleITK version: {sitk.Version()}\n")

if __name__ == "__main__":
    version()
    synthetic_img = generating_synthetic_image()
    true_img = reading_true_image()

    test(synthetic_img)
    test(true_img)

Messages for the two SimpleITK versions:

------------------------ SimpleITK version 1.0.1 ----------------------------
Operating system: Darwin-19.5.0-x86_64-i386-64bit

Python version: 3.6.6 (default, Nov 25 2019, 13:38:31) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.12)]

SimpleITK version: SimpleITK Version: 1.0.1 (ITK 4.11)
Compiled: Aug  2 2017 21:20:41


Generating synthetic image...
Reading true image...
Testing: Synthetic image
(0, 1, 2, 3)
Testing: True image
(0, 1, 2, 3)
------------------------------------------------------------------------ 


------------------------ SimpleITK version 2.0rc1 ----------------------------
Operating system: Darwin-19.5.0-x86_64-i386-64bit

Python version: 3.6.6 (default, Nov 25 2019, 13:38:31) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.12)]

SimpleITK version: SimpleITK Version: 2.0.0rc1 (ITK 5.1)
Compiled: Mar 10 2020 01:17:09


Generating synthetic image...
Reading true image...
Testing: Synthetic image
(2, 3, 1, 0)
Testing: True image
(2, 3, 1, 0)
------------------------------------------------------------------------ 


NOTE: I also noticed that the label ordered varied for the 2.0rc1 version between runtimes, and there was not always agreement between the label order for the synthetic and true image within same runtime.

Hope this make sense, and that you are able to reproduce the error.

**Comment by blowekamp** [comment] 2020-06-29 14:48
Regarding the ordering, in ITKv5 the data structure to store the labels changed from the C++ [`std::map`](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwidjMC9n6fqAhWRYDUKHe2ICkQQFjAAegQIBRAB&url=https%3A%2F%2Fen.cppreference.com%2Fw%2Fcpp%2Fcontainer%2Fmap&usg=AOvVaw39Z3umI4NmAmKJ6Jc3_fSb) to the [`std::unordered_map`](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwihnsnHn6fqAhVil3IEHXUpB4oQFjAAegQIARAB&url=http%3A%2F%2Fwww.cplusplus.com%2Freference%2Funordered_map%2Funordered_map%2F&usg=AOvVaw0AeCfseOFY0qbK6pgYHo60). The new unordered_map uses a hash data structure as opposed to a tree, so the order of the new structure will be different, and may change form system to system. This is a side effect of changing the ITK major version from 4 to 5. You can always sort the returned list if needed.

I am inclined to label the ordering bug as "Won't Fix" as it is a change in ITK's behavior. Does this behavior/change cause any problems?

I have been able to reproduce the Warning by calling "DebugOn" followed by `Execute`.

**Comment by blowekamp** [comment] 2021-04-12 17:19
The warning has been addressed in ITK.

**Closed by blowekamp** 2021-04-12 17:19 UTC
Labels: Bug Report, Won't Fix
