### ISSUE TITLE
ImageFileReader extracts wrong subregion of the data if the ExtractIndex larger than 1024

### ISSUE THREAD

**Issue by dichen9412** [SimpleITK/SimpleITK#1628] opened 2022-04-16 21:13 UTC
Hi, 
I was following the tutorial https://simpleitk.readthedocs.io/en/master/link_AdvancedImageReading_docs.html to extract a large file by extracting subregions given my memory constraints. However, I notice that if I do something like 👍 file_reader.SetExtractIndex(current_index) with any dimension of "current_index" larger than 1024, the file_reader gives me wrong subregion of the data.

Could you fix it?
Best,
Di

**Comment by zivy** [comment] 2022-04-20 23:44
Hello @dichen9412,

The description of the issue is too broad. It isn't clear what "wrong subregion" means and what exactly is causing the problem. Please provide a minimal working example illustrating the issue. Below is some code showing that the extract region works as expected with an index larger than 1024. Feel free to modify this code to illustrate the issue.

```
import SimpleITK as sitk

file_name = 'large_image.mha'

image = sitk.Image([5000,5000,50], sitk.sitkUInt8)
image.SetOrigin([0.6,0.7,0.8])
image.SetSpacing([0.5,0.5,0.5])
sitk.WriteImage(image, file_name)

# Read image information without reading the bulk data.
file_reader = sitk.ImageFileReader()
file_reader.SetFileName(file_name)
file_reader.ReadImageInformation()
print(f'image origin: {file_reader.GetOrigin()}\nimage size: {file_reader.GetSize()}\nimage spacing: {file_reader.GetSpacing()}')

current_index = [1025, 1025, 0]
extract_size = [100, 100, 50]
print(f'index physical position: {image.TransformIndexToPhysicalPoint(current_index)}')
file_reader.SetExtractIndex(current_index)
file_reader.SetExtractSize(extract_size)
subimage = file_reader.Execute()
print(f'subimage origin: {subimage.GetOrigin()}\nsubimage size: {subimage.GetSize()}\nsubimage spacing: {subimage.GetSpacing()}')
```

**Comment by dichen9412** [comment] 2022-04-21 00:31
Hi Zivy, 

Thanks for replying to my issue! 
I can't give you the exact data I use but I think I can illustrate the problem better:

In your code, you extracted a region without any error prompts. 
However, your entire image is probably just 0s. So you don't see the problem. 
Can you fill your image such that image[i, :, :] are filled with number i. 
Then you can check if your code extracts the right region of the image. 
With your code and the image I described above, the region should have numbers ranging from 1025 to 1125.
However, if the index is larger than 1024, it extracts from the beginning, i.e., [0, 0, 0], resulting in a sub-image with numbers ranging from 0 to 100. 

Hope my suggestion reproduces the bug on your side. 

Best,
Di

**Comment by zivy** [comment] 2022-04-21 14:12
Hello @dichen9412,

Based on your suggestion, below is a minimal working example illustrating that reading the subregion works as expected:
```
import SimpleITK as sitk
import numpy as np

file_name = 'large_image.mha'

image = sitk.GetImageFromArray(np.arange(5000*5000*50).reshape((50,5000,5000)))
sitk.WriteImage(image, file_name)

current_index = [1025, 1025, 0]
extract_size = [100, 100, 50]
file_reader = sitk.ImageFileReader()
file_reader.SetFileName(file_name)
file_reader.SetExtractIndex(current_index)
file_reader.SetExtractSize(extract_size)
subimage = file_reader.Execute()

print(sitk.GetArrayViewFromImage(subimage))
```

**Comment by dichen9412** [comment] 2022-04-21 15:22
Hi zivy, 

Thanks for following up on this issue. I just tried to reproduce this with my minimal code on a MacBook pro. However, I don't see the issue there. Then I go back to my server and the issue exists again. My server is an AWS P3.x8large instance with 
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.7 LTS
Release:	16.04
Codename:	xenial
. 
The Simpleitk version I use on both my MacBook Pro and the ubuntu is 1.2.4. Interestingly, I can reproduce the bug on ubuntu but not on my MacBook pro. 
The input file is a .nii.gz file with a dtype=float64. I also tried on the same size but dtype=int8. The issue still exists. 
(I can send you the small segmentation mask file via email if you want.)
Let me know if you need any further information.

Here is my code: (on Mac the diff is 0 while on ubuntu it was  > 0).


"""
Script to reformat 2020 data and explore

"""
import os
import zipfile
import shutil
#import nibabel as nib
import numpy as np
from skimage import measure
import time
import SimpleITK as sitk
import tracemalloc
import gc

def reverse_axes(image):
    return np.transpose(image, tuple(reversed(range(image.ndim))))


def read_image(imagefile, verbose=True):
    file_reader = sitk.ImageFileReader()
    file_reader.SetFileName(imagefile)
    file_reader.ReadImageInformation()


    #image = sitk.ReadImage(imagefile)

    raw_direction = np.asarray(file_reader.GetDirection()).reshape(3, 3)
    direction = np.zeros((3, 3))
    for i in range(3):
        idx = np.argmax(abs(raw_direction[:, i]))
        if raw_direction[idx][i] > 0:
            direction[idx][i] = 1
        else:
            direction[idx][i] = -1
    header = {
        'size': file_reader.GetSize(),
        'spacing': file_reader.GetSpacing(),
        'origin': file_reader.GetOrigin(),
        'direction': direction,
        'raw_direction': file_reader.GetDirection(),
    }
    if (verbose):
        #print("dtype", data.dtype)
        print("raw_direction", raw_direction)
        print("direction", direction)
        print("shape", header['size'])
        print("raw_spacing", header['spacing'])

    image_size = file_reader.GetSize()
    tot_vol = image_size[0] * image_size[1] * image_size[2]

    extract_size = list(file_reader.GetSize())
    dim = np.argmax(extract_size)

    parts = min(int(tot_vol / (512 * 512 * 900)) + 1, extract_size[dim])
    extract_size[dim] = (extract_size[dim] - 1) // parts + 1
    current_index = [0, 0, 0]

    print("dim", dim, "parts", parts)
    data = np.zeros(image_size, dtype="float64")

    for i in range(parts):
        current_index[dim] = i * extract_size[dim]
        if (i == parts -1):
            extract_size[dim] = image_size[dim] - current_index[dim]

        print("current_index", current_index, "extract_size", extract_size)
        file_reader.SetFileName(imagefile)
        file_reader.SetExtractIndex(current_index)
        file_reader.SetExtractSize(extract_size)
        sub_image1 = file_reader.Execute()
        sub_data = sitk.GetArrayFromImage(sub_image1)
        #del sub_image1
        #sub_data = np.clip(sub_data, -1000, 10000, out=sub_data).astype("float16", copy=False)
        sub_data = reverse_axes(sub_data)
        l = np.asarray(current_index, dtype="int")
        r = l + np.asarray(extract_size, dtype="int")
        print("sub_data-%d"%i, sub_data.shape, "l", l, "r", r)
        data[l[0]:r[0], l[1]:r[1], l[2]:r[2]] = sub_data

        import matplotlib.pyplot as plt
        n_col = 3
        n_row = 1
        fig, axes = plt.subplots(n_row, n_col, figsize = (n_col * 5, n_row * 5))
        axes[0].imshow(data[data.shape[0]//2].astype("float32"))
        axes[1].imshow(data[:,data.shape[1]//2].astype("float32"))
        axes[2].imshow(data[:, :, data.shape[2]//2].astype("float32"))

        plt.show()
    del sub_image1

    gc.collect()
    return data, header


imagefile = "/DRAI/Spine/Data/New/verse602_CT-iso_seg.nii.gz"
image1 = sitk.ReadImage(imagefile)
data1 = sitk.GetArrayFromImage(image1)
data1 = reverse_axes(data1)

print("data1", data1.shape, image1.GetSize())



data2, header = read_image(imagefile)

print("data2", data2.shape)

print("diff", np.mean(abs(data1-data2)))















#

**Comment by zivy** [comment] 2022-04-21 15:32
Hello @dichen9412,

Not sure what is the issue then. More likely it is on your side than in SimpleITK. 

Having said that, you appear to be working in a very old environment, ubuntu 16.04 which reached its end of life last year and SimpleITK 1.2.4 which was released 2.5 years ago, Nov. 2019.

As a first step I would recommend moving to a 2.x version of SimpleITK, note that it will not bebackwards compatible with the 1.x versions (see [migration guide](https://simpleitk.readthedocs.io/en/master/migrationGuide2.0.html)). If the problem still exists there then we can further look into it.

**Comment by dichen9412** [comment] 2022-04-21 15:37
Hi zivy,

Just for you to know，I tried to upgrade to the latest simpleitk version 2.x.x but the problem is there.

Best，
Di

**Comment by dichen9412** [comment] 2022-04-21 20:15
Hi zivy,

Here is a short example to reproduce the bug:
(I actually tried this with another machine ubuntu18.04 + simpleitk 2.1.1.2 and it still gives wrong results. (The behavior on ubuntu 16.04 and 18.04 are a bit different but are both wrong.))



import SimpleITK as sitk
import numpy as np

file_name = 'large_image.nii.gz'
data = np.zeros((512, 512, 2023), dtype="float64")
for i in range(2023):
    data[:, :, i] = int(i // 1000)
image = sitk.GetImageFromArray(data.transpose(2, 1, 0))
print("image size", image.GetSize())
sitk.WriteImage(image, file_name)
current_index = [0, 0, 1200]
extract_size = [100, 100, 50]
file_reader = sitk.ImageFileReader()
file_reader.SetFileName(file_name)
file_reader.SetExtractIndex(current_index)
file_reader.SetExtractSize(extract_size)
subimage = file_reader.Execute()
print(np.mean(sitk.GetArrayViewFromImage(subimage)))
print(np.mean(data[0:100, 0:100, 1200:1250]))

**Comment by zivy** [comment] 2022-04-21 20:58
Hello @dichen9412,

The code is very strange, some operations do not make sense. For example `data[:, :, i] = int(i // 1000)`. This fills the image slices 0-999 with zero, slices 1000-1999 with one and slices 2000-2022 with two. I suspect this is not what you want.

Also, do not use mean to compare two images, subtract them and look at the min and max. Make sure that the indexing is correct. In SimpleITK index order is [x,y,z], and in numpy it is [z,y,x].

Finally, please format code using the [GitHub syntax](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).

**Comment by dichen9412** [comment] 2022-04-21 21:06
Hi zivy, 

I give the strange value to the scan just to differentiate different slices. So the slices 0-999 are just 0s and 1000-1999 with 1s and 2000-2022 with 2s. 
The subregion starting with slice 1200 should be all 1s. So the average should be 1. However, the average of the subregion doesn't give the right value. On ubuntu 16.04 it was 0. On ubuntu 18.04 it was a very large number. 
I'm pretty sure the indexing is correct since I have transposed the data to form the image. 

Best,
Di

**Comment by blowekamp** [comment] 2022-07-20 15:00
Thank you for the question. Hopefully the problem has been resolved since it was asked.

**Closed by blowekamp** 2022-07-20 15:00 UTC
Labels: Question
